[package]
name = "wesl_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.11.9"
image = { version = "0.25.10", features = ["png", "jpeg"] }
log = "0.4.29"
notify-debouncer-mini = "0.7.0"
pollster = "0.4.0"
tobj = { version = "4.0.3", default-features = false, features = ["async", "tokio"] }
wesl = "0.3.2"
wgpu = "28.0.0"
winit = "0.30.13"

[lib]
crate-type = ["rlib"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

